---
- name: Install common packages and make sure the system is up to date
  hosts: all
  remote_user: root

  tasks:
  - name: Install common packages
    yum:
      name:
        - mlocate                #locate command
        - net-tools              #ifconfig command
        - vim                    #Vim
      state: latest
  - name: Update installed packages
    yum: name=* state=latest update_cache=yes
