---
- name: Install Jenkins
  hosts: Jenkins1
  remote_user: root

  tasks:
  - name: Enable the EPEL Repo
    yum: name=epel-release state=latest
  - name: Import Jenkins key
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Setup the Jenkins repo
    yum_repository:
      name: jenkins
      description: Jenkins
      baseurl: http://pkg.jenkins.io/redhat
      gpgcheck: yes
  - name: Install Jenkins and its prerequisites
    yum:
      name:
        - java-1.8.0-openjdk
        - jenkins
      state: latest
  - name: Enable the Jenkins daemon and ensure it is not masked
    systemd:
      name: jenkins
      enabled: yes
      masked: no
  - name: Start Jenkins
    service: name=jenkins state=started
  - name: Configure firewalld to trust an IP range
    firewalld:
      source: 192.168.122.0/24
      zone: trusted
      permanent: yes
      immediate: yes
      state: enabled
  - name: Configure firewalld to allow connections to Jenkins
    firewalld:
      port: 8080/tcp
      zone: trusted
      permanent: yes
      immediate: yes
      state: enabled

  handlers:
  - name: Restart Jenkins
    service: name=jenkins state=restarted
