---
- name: Install Jenkins
  hosts: Jenkins1
  remote_user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: Enable the EPEL Repo
    yum: name=epel-release state=latest
  - name: Import Jenkins key
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Setup the Jenkins repo
    yum_repository:
      name: jenkins
      description: Jenkins
      baseurl: http://pkg.jenkins.io/redhat
      gpgcheck: yes
  - name: Install Jenkins and its prerequisites
    yum:
      name:
        - java-1.8.0-openjdk
        - jenkins
      state: latest
  - name: Enable the Jenkins daemon and ensure it is not masked
    systemd:
      name: jenkins
      enabled: yes
      masked: no
  - name: Start Jenkins
    service: name=jenkins state=started

  handlers:
  - name: Restart Jenkins
    service: name=jenkins state=restarted
