---
- name: Install, enable and start Jenkins
  hosts: Jenkins1
  remote_user: centos
  become: yes
  become_method: sudo

  tasks:
#  - name: Install common packages
#    yum:
#      name:
#        - wget                   #Required to setup the Jenkins repo
#      state: latest
  - name: Enable the EPEL Repo
    yum: name=epel-release state=latest
  - name: Import Jenkins key
#    command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Setup the Jenkins repo
#    command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    yum_repository:
      name: jenkins
      description: Jenkins YUM repo
      baseurl: http://pkg.jenkins-ci.org/redhat/jenkins.repo
  - name: Install Jenkins and its prerequisites
    yum:
      name:
        - java-1.8.0-openjdk
        - jenkins
      state: latest
  - name: Enable the Jenkins daemon and ensure it is not masked
    systemd:
      name: jenkins
      enabled: yes
      masked: no
  - name: Start Jenkins
    service: name=jenkins state=started
#  - name: Write Jenkins config
#    template:
#      src: jenkins.j2
#      dest: /etc/jenkins/jenkins.conf
#      owner: root
#      group: root
#      mode: '0644'
#    notify:
#    - Restart Jenkins

  handlers:
  - name: Restart Jenkins
    service: name=jenkins state=restarted
