---
- name: Install HAProxy
  hosts: load_balancers
  remote_user: root

  tasks:
  - name: Install common packages
    yum:
      name:
        - policycoreutils-python #Required to set SELinux tags
      state: latest
  - name: Install HAProxy
    yum:
      name:
        - haproxy
      state: latest
  - name: Enable the HAProxy daemon and ensure it is not masked
    systemd:
      name: haproxy
      enabled: yes
      masked: no
  - name: Start HAProxy
    service: name=haproxy state=started
  - name: Configure firewalld to trust an IP range
    firewalld:
      source: 192.168.122.0/24
      zone: trusted
      permanent: yes
      immediate: yes
      state: enabled
  - name: Configure firewalld to allow connections to HAProxy
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Configure firewalld to allow connections to HAProxy
    firewalld:
      service: https
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Configure firewalld to allow connections to HAProxy status page
    firewalld:
      port: 8404/tcp
      zone: trusted
      permanent: yes
      immediate: yes
      state: enabled
  - name: Set SELinux booleans for HAProxy
    command: /usr/sbin/setsebool -P haproxy_connect_any=1
  - name: Write HAProxy config
    template:
      src: haproxy.j2
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0644'
    notify:
    - Restart HAProxy

  handlers:
  - name: Restart HAProxy
    service: name=haproxy state=restarted
