---
- name: Install Apache, integrate it with Python and setup the job_matchmaker app
  hosts: web_servers
  remote_user: root
  vars:
    home_folder: /root

  tasks:
  - name: Install common packages
    yum:
      name:
        - gcc                    #Required to compile Python modules
        - policycoreutils-python #Required to set SELinux tags
        - python-setuptools      #Required by CentOS 7 1810 to install Python3 modules using the pip Anisble module
      state: latest
  - name: Install Apache
    yum: name=httpd state=latest
  - name: Enable the Apache daemon and ensure it is not masked
    systemd:
      name: httpd
      enabled: yes
      masked: no
  - name: Start Apache
    service: name=httpd state=started
  - name: Configure firewalld allowing http
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Configure firewalld allowing https
    firewalld:
      service: https
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  - name: Install Python3
    yum:
      name:
        - python3
        - python3-devel
      state: latest
  - name: Install PostgreSQL
    yum:
      name:
        - postgresql
        - postgresql-devel
      state: latest
  - name: Install Python3 modules using Pip
    pip:
      executable: /usr/bin/pip3
      name:
      - bs4
      - psycopg2
      - PyYAML
  - name: Create a /var/www/python directory if it does not exist
    file:
      path: /var/www/python
      owner: apache
      group: apache
      state: directory
      mode: '0755'
  - name: Recursively change ownership /var/www/python directory
    file:
      path: /var/www/python
      state: directory
      recurse: yes
      owner: apache
      group: apache
  - name: Set SELinux boolean to allow Apache to read/write
    seboolean:
      name: allow_httpd_anon_write
      state: yes
      persistent: yes
  - name: Set SELinux boolean to allow Apache to network connect
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
  - name: Set SELinux boolean to allow Apache to network connect to a database
    seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes
  - name: Set SELinux context for /var/www/python
    sefcontext:
      target: '/var/www/python(/.*)?'
      setype: httpd_sys_script_exec_t
      state: present
  - name: Write Apache config for Python
    template:
      src: python.j2
      dest: /etc/httpd/conf.d/python.conf
      owner: root
      group: root
      mode: '0644'
    notify:
    - Restart Apache
  - name: Copy app files
    copy: src={{ item.src }} dest={{ item.dest }} owner=apache group=apache mode='0755'
    with_items:
      - { src: '../find_jobs.py', dest: '/var/www/python/find_jobs.py' }
      - { src: '../helper.py', dest: '/var/www/python/helper.py' }
      - { src: '../helper.py', dest: '{{home_folder}}/helper.py' }
      - { src: '../rate_job.py', dest: '/var/www/python/rate_job.py' }
      - { src: '../search.css', dest: '/var/www/html/search.css' }
      - { src: '../search.html', dest: '/var/www/html/search.html' }
      - { src: '../search.js', dest: '/var/www/html/search.js' }
      - { src: '../setup_database.py', dest: '{{home_folder}}/setup_database.py' }
      - { src: '../show_jobs.py', dest: '/var/www/python/show_jobs.py' }
  - name: Copy app conf file
    template:
      src: job_matchmaker.j2
      dest: /etc/job_matchmaker.conf
      owner: apache
      group: apache
      mode: '0400'
  - name: Ensure the database is setup
    command: /usr/bin/python3 {{home_folder}}/setup_database.py

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
